name: docker push

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  Pushing-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          cache-from: |
            type=gha
          cache-to: |
            type=gha,mode=max
          load: true
          pull: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.docker_tag }}
          build-args: |
            EMULATOR_DEVICE=${{ matrix.emulator_device }}
            ARCH=x86_64
            EMULATOR_NAME=${{ matrix.emulator_name }}

    strategy:
       matrix:
        emulator_device:
          - pixel_c
          - Nexus 6
        emulator_name:
          - pixel_c
          - nexus
        docker_tag: ["nexus6_playstore", "pixelC_tablet_playstore"]
        exclude:
          - emulator_device: Nexus 6
            emulator_name: nexus
            docker_tag: pixelC_tablet_playstore
          - emulator_device: Nexus 6
            emulator_name: pixel_c
            docker_tag: pixelC_tablet_playstore
          - emulator_device: Nexus 6
            emulator_name: pixel_c
            docker_tag: nexus6_playstore
          - emulator_device: pixel_c
            emulator_name: nexus
            docker_tag: nexus6_playstore
          - emulator_device: pixel_c
            emulator_name: nexus
            docker_tag: pixelC_tablet_playstore
          - emulator_device: pixel_c
            emulator_name: pixel_c
            docker_tag: nexus6_playstore
